# Generated by Django 4.0.5 on 2023-02-17 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancecategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='owner',
        ),
        migrations.AddField(
            model_name='attendance',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
    ]
