# Generated by Django 4.0.5 on 2023-02-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=255)),
                ('weekend', models.BooleanField()),
                ('holiday', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='year_month',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
