# Generated by Django 4.0.5 on 2023-02-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_calendar_attendance_year_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='profile',
        ),
    ]
