# Generated by Django 4.0.5 on 2023-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attendance_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='year_month',
        ),
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
