# Generated by Django 4.0.5 on 2023-02-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_attendance_year_month_attendance_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
