# Generated by Django 4.0.5 on 2023-02-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attendance_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['date'], 'verbose_name_plural': 'Calendar'},
        ),
        migrations.AddField(
            model_name='calendar',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.IntegerField(),
        ),
    ]
