# Generated by Django 4.0.5 on 2023-02-23 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_calendar_options_calendar_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAggMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthId', models.UUIDField(default=uuid.uuid4)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('month', models.DateField()),
                ('duration', models.IntegerField()),
                ('work_hours', models.IntegerField()),
                ('vacation', models.IntegerField()),
                ('extra_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
