# Generated by Django 4.0.5 on 2023-02-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attendanceaggmonth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceaggmonth',
            name='extra_hours',
        ),
        migrations.RemoveField(
            model_name='attendanceaggmonth',
            name='vacation',
        ),
        migrations.RemoveField(
            model_name='attendanceaggmonth',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendanceaggmonth',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
