# Generated by Django 4.0.5 on 2023-02-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_attendance_profile'),
        ('userprofile', '0002_alter_userprofile_profileid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
