# Generated by Django 4.0.5 on 2023-02-19 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profileId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
