# Generated by Django 4.0.5 on 2023-02-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_userprofile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fteValue',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
        ),
    ]
