# Generated by Django 4.0.5 on 2023-02-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='year_month',
        ),
        migrations.AddField(
            model_name='project',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
