# Generated by Django 4.0.5 on 2023-02-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_year_month_project_month_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
