# Generated by Django 4.0.5 on 2023-02-19 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectsaggmonth_monthid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsaggmonth',
            old_name='hours',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='projectsaggmonth',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
